version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_container
    environment:
      POSTGRES_DB: insight
      POSTGRES_USER: insight
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - insightnetwork

networks:
  insightnetwork:
    driver: bridge
