version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_container
    environment:
      POSTGRES_DB: insight
      POSTGRES_USER: insight
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - insightnetwork

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile-php4
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8080:8080'
    volumes:
      - '.:/var/www/html'
    networks:
      - insightnetwork

networks:
  insightnetwork:
    driver: bridge
